#pragma once

#include "Behaviour/Behaviour.h"
#include "GameObject/ObjectHandle.h"
#include "Networking/Serialization/RegistrationBase.h"

#include <vector>

class TilemapComponent;

/**
 * @brief Builds static physics colliders from a TilemapComponent.
 *
 * Colliders are generated by merging contiguous collidable tiles into
 * axis-aligned rectangles. This keeps the number of physics bodies scalable
 * for large maps.
 */
class TilemapColliderComponent final: public Behaviour,
                                      RegistrationBase<TilemapColliderComponent>
{
public:
	TilemapColliderComponent() = default;
	~TilemapColliderComponent() override = default;

	static constexpr const char* name()
	{
		return "TilemapCollider";
	}
	const char* getName() const override { return name(); }

	/**
	 * @brief Explicitly set the tilemap to bake from (defaults to same GameObject).
	 */
	void setTilemapComponent(TilemapComponent* tilemap);
	TilemapComponent* getTilemapComponent() const;

	/**
	 * @brief Automatically bake colliders in onStart().
	 */
	void setAutoBake(bool enabled);
	bool getAutoBake() const;

	/**
	 * @brief Build colliders immediately. Clears any previously baked colliders.
	 */
	void bakeColliders();

	/**
	 * @brief Remove any previously baked colliders.
	 */
	void clearColliders();

	void serialize(WriteArchive& archive) const override;
	void deserialize(ReadArchive& archive) override;

protected:
	void onStart() override;
	void onDestroy() override;

private:
	TilemapComponent* tilemapComponent = nullptr;
	bool autoBake = true;
	bool hasBaked = false;
	std::vector<ObjectHandle> colliderHandles;
};
